### ISSUE TITLE
Telerik UI Nuget Source 401 unauthorised

### ISSUE THREAD

**Issue by ColdstarJoey** [pcislo/vscode-nuget-gallery#131]
When I add the source `{"name": "Telerik UI","url": "https://nuget.telerik.com/v3/index.json"}` and I have the latest version of CredentialProivder located at `{user-profile}/nuget/plugins/netcore/CredentialProvider.Microsoft`

it comes back with in the terminal

The terminal process failed to launch: Path to shell executable "dotnet "/Users/mainuser/nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll"" does not exist. 

and in the output it returns Error: there is no registered task type 'nuget'. Did you miss installing an extension that provides a corresponding task provider?

the dll is in the folder but this source also needs a username and password, any ideas?

this works in VS 2022 Mac perfectly, just need it to in VS code

**Comment by pcislo** [comment]
Could you try to run this command in a console and see if the executable is found? `dotnet "/Users/mainuser/nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll"`

What version of the extension are you using?

**Comment by mkalinski93** [comment]
Hey, I´ve also got the same error. This is the debug log from the console you´ve asked for:

```
 dotnet "/Users/USER/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll" -C False -R -U https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json -V "Debug"
[Verbose] [CredentialProvider]Running in stand-alone mode
[Verbose] [CredentialProvider]Command-line v1.2.2: /Users/USER/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll -C False -R -U https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json -V Debug
[Verbose] [CredentialProvider]Handling auth request, Uri: https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json, IsRetry: False, IsNonInteractive: False, CanShowDialog: False
[Verbose] [CredentialProvider]URI: https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
[Verbose] [CredentialProvider]VstsBuildTaskServiceEndpointCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet with external endpoint credentials. Appropriate environment variable needs to be set.
[Verbose] [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTaskServiceEndpoint.VstsBuildTaskServiceEndpointCredentialProvider, cannot provide credentials for https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
[Verbose] [CredentialProvider]VstsBuildTaskCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet. Appropriate environment variables must be set.
[Verbose] [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTask.VstsBuildTaskCredentialProvider, cannot provide credentials for https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
[Verbose] [CredentialProvider]GET https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
[Verbose] [CredentialProvider]VstsCredentialProvider - https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json is not an Azure Artifacts feed.
[Verbose] [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider, cannot provide credentials for https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
[Verbose] [CredentialProvider]Unable to acquire credentials.
```

I´m trying to add a private gitlab feed on my MacBook M1.

**Comment by pcislo** [comment]
> Hey, I´ve also got the same error. This is the debug log from the console you´ve asked for:
> 
> ```
>  dotnet "/Users/USER/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll" -C False -R -U https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json -V "Debug"
> [Verbose] [CredentialProvider]Running in stand-alone mode
> [Verbose] [CredentialProvider]Command-line v1.2.2: /Users/USER/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll -C False -R -U https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json -V Debug
> [Verbose] [CredentialProvider]Handling auth request, Uri: https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json, IsRetry: False, IsNonInteractive: False, CanShowDialog: False
> [Verbose] [CredentialProvider]URI: https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
> [Verbose] [CredentialProvider]VstsBuildTaskServiceEndpointCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet with external endpoint credentials. Appropriate environment variable needs to be set.
> [Verbose] [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTaskServiceEndpoint.VstsBuildTaskServiceEndpointCredentialProvider, cannot provide credentials for https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
> [Verbose] [CredentialProvider]VstsBuildTaskCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet. Appropriate environment variables must be set.
> [Verbose] [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTask.VstsBuildTaskCredentialProvider, cannot provide credentials for https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
> [Verbose] [CredentialProvider]GET https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
> [Verbose] [CredentialProvider]VstsCredentialProvider - https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json is not an Azure Artifacts feed.
> [Verbose] [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider, cannot provide credentials for https://gitlab.com/api/v4/projects/ID/packages/nuget/index.json
> [Verbose] [CredentialProvider]Unable to acquire credentials.
> ```
> 
> I´m trying to add a private gitlab feed on my MacBook M1.

Could you create a nuget.config file with the necessary credentials to access the GitLab registry and check whether it works?

**Comment by Jomontalvo** [comment]
Hi, my environment is VSCode for MacOs, and .Net 9.0.4
https://nuget.telerik.com/v3/index.json Telerik Nuget Feed produce same error.

This nugget needs credentials, and I add this info in Nuget.Config.

This is the command the extension attempts to execute:
`dotnet /Users/om/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll -C False -R -U https://nuget.telerik.com/v3/index.json -V Debug`

And the result is:
```
[Verbose] [CredentialProvider]Running in stand-alone mode
[Verbose] [CredentialProvider]Command-line v1.4.1+3c3ac17018f437ac773b126ebb87fc9accaeef16: /Users/om/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll -C False -R -U https://nuget.telerik.com/v3/index.json -V Debug
[Verbose] [CredentialProvider]Handling auth request, Uri: https://nuget.telerik.com/v3/index.json, IsRetry: False, IsNonInteractive: False, CanShowDialog: False
[Verbose] [CredentialProvider]URI: https://nuget.telerik.com/v3/index.json
[Verbose] [CredentialProvider]VstsBuildTaskServiceEndpointCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet with external endpoint credentials. Appropriate environment variable needs to be set.
[Verbose] [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTaskServiceEndpoint.VstsBuildTaskServiceEndpointCredentialProvider, cannot provide credentials for https://nuget.telerik.com/v3/index.json
[Verbose] [CredentialProvider]VstsBuildTaskCredentialProvider - This credential provider must be run under the Team Build tasks for NuGet. Appropriate environment variables must be set.
[Verbose] [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.VstsBuildTask.VstsBuildTaskCredentialProvider, cannot provide credentials for https://nuget.telerik.com/v3/index.json
[Verbose] [CredentialProvider]GET https://nuget.telerik.com/v3/index.json
[Verbose] [CredentialProvider]VstsCredentialProvider - https://nuget.telerik.com/v3/index.json is not an Azure Artifacts feed.
[Verbose] [CredentialProvider]Skipping NuGetCredentialProvider.CredentialProviders.Vsts.VstsCredentialProvider, cannot provide credentials for https://nuget.telerik.com/v3/index.json
[Verbose] [CredentialProvider]Unable to acquire credentials.
```
Web Developer Tools error is:
```
ERR [Extension Host] Error: Command failed: dotnet "/Users/om/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll" -N -F Json -U https://nuget.telerik.com/v3/index.json
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:916:11)
    at execSync (node:child_process:988:15)
    at node:electron/js2c/node_init:2:17313
    at NuGetApi.GetCredentials (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29768:18)
    at /Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29571:25
    at Axios.request (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29155:14)
    at NuGetApi.ExecuteGet (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29716:22)
    at NuGetApi.EnsureSearchUrl (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29700:20)
    at NuGetApi.GetPackageAsync (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29610:5)
    at GetPackage.HandleAsync (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:33970:27)
    at Mediator.HandleRequest (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:26135:20)

```
and

```
[Extension Host] Error: Command failed: dotnet "/Users/om/.nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll" -N -F Json -U https://nuget.telerik.com/v3/index.json
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:916:11)
    at execSync (node:child_process:988:15)
    at node:electron/js2c/node_init:2:17313
    at NuGetApi.GetCredentials (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29768:18)
    at /Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29571:25
    at Axios.request (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29155:14)
    at NuGetApi.ExecuteGet (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29716:22)
    at NuGetApi.EnsureSearchUrl (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29700:20)
    at NuGetApi.GetPackageAsync (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:29610:5)
    at GetPackage.HandleAsync (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:33970:27)
    at Mediator.HandleRequest (/Users/om/.vscode/extensions/patcx.vscode-nuget-gallery-1.2.4/dist/extension.js:26135:20)

```
